language: node_js
node_js:
  - '7'
env:
  - NODE_ENV=development
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_28afe64cd384_key -iv $encrypted_28afe64cd384_iv -in travis.enc -out ~/.ssh/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 66.112.210.21\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - yarn
addons:
  ssh_known_hosts: 66.112.210.21

script:
  - npm run build
  - rsync -r --delete -e 'ssh -p 26544' ./dist root@66.112.210.21:/var/cms-backend/public
